all:
		rm -rf bin
		mkdir bin
		cp src/lexer.py bin/lexer.py
		cp src/LALR_parser.py bin/irgen
		cp src/new_sym_table.py bin/new_sym_table.py
		cp src/three_address_code.py bin/three_address_code.py
		chmod +x bin/irgen
clean:
		rm -rf bin
